
-- 1번
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1;



-- 2번
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;



-- 3번
SELECT STUDENT_NAME AS "학생이름", STUDENT_NO AS "학번", STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A' AND SUBSTR(STUDENT_ADDRESS,1,3) IN('경기도','강원도')
ORDER BY 1;


-- 4번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE  DEPARTMENT_NAME = '법학과'
ORDER BY 2;


-- 5번
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00')
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC, 1;


-- 6번
SELECT STUDENT_NO AS "학생 번호", STUDENT_NAME AS "학생 이름", DEPARTMENT_NAME AS "학과 이름"
FROM TB_STUDENT 
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;



-- 7번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);


-- 8번
SELECT CLASS_NAME, PROFESSOR_NAME 
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);



-- 9번
SELECT CLASS_NAME, PROFESSOR_NAME 
FROM TB_CLASS C
    JOIN TB_CLASS_PROFESSOR CP USING(CLASS_NO)
    JOIN TB_PROFESSOR TP USING(PROFESSOR_NO)
    JOIN TB_DEPARTMENT D ON D.DEPARTMENT_NO = C.DEPARTMENT_NO
WHERE CATEGORY = '인문사회';


-- 10번
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;


-- 11번
SELECT D.DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_DEPARTMENT D
    JOIN TB_STUDENT USING(DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE STUDENT_NO = 'A313047'; 


-- 12번
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
    JOIN TB_GRADE USING(STUDENT_NO)
    JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND SUBSTR(TERM_NO,1,4) = 2007
ORDER BY 1;



-- 13번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    LEFT OUTER JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;


-- 14번
SELECT STUDENT_NAME AS 학생이름, NVL(PROFESSOR_NAME,'지도교수 미지정') AS 지도교수
FROM TB_STUDENT S
    LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
    JOIN TB_DEPARTMENT D ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;
    
    
-- 15번
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, AVG(POINT)
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0;

-- 16번
SELECT CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS
    JOIN TB_GRADE USING(CLASS_NO)
    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND SUBSTR(CLASS_TYPE,1,2) = '전공' 
GROUP BY CLASS_NO, CLASS_NAME;


-- 17번
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');


-- 18번
SELECT STUDENT_NO, STUDENT_NAME FROM(  
    SELECT STUDENT_NO, STUDENT_NAME
    FROM TB_STUDENT     
        JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
        JOIN TB_GRADE USING(STUDENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과' 
    GROUP BY STUDENT_NO, STUDENT_NAME
    ORDER BY AVG(POINT) DESC
    )
WHERE ROWNUM = 1;




-- 19번
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1) 
FROM TB_DEPARTMENT
    JOIN TB_CLASS USING(DEPARTMENT_NO)
    JOIN TB_GRADE USING (CLASS_NO)
WHERE SUBSTR(CLASS_TYPE,1,2) = '전공' AND CATEGORY = '자연과학' 
    GROUP BY DEPARTMENT_NAME
ORDER BY 1;




SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;










