
-- 1번
SELECT STUDENT_NO, STUDENT_NAME, 
TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;


-- 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;


-- 3번
SELECT PROFESSOR_NAME AS "교수이름", 
EXTRACT(YEAR FROM SYSDATE)-(TO_NUMBER(SUBSTR(PROFESSOR_SSN,1,2))+1900) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 나이 ASC;
    

-- 4번
SELECT SUBSTR(PROFESSOR_NAME,2) FROM TB_PROFESSOR;


-- 5번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - TO_NUMBER(SUBSTR(STUDENT_SSN,1,2)) - 1900 > 19;


-- 6번
    SELECT TO_CHAR(TO_DATE(20201225), 'DAY') FROM DUAL;


-- 7번
-- 뒤 두자리가 YY이면 앞에 2000년대임
-- 뒤 두자리가 RR이면 앞에 49까지만 2000년도며  50부터는 1900년도임
SELECT EXTRACT(YEAR FROM TO_DATE('99/10/11','YY/MM/DD')), EXTRACT(YEAR FROM TO_DATE('49/10/11','YY/MM/DD')),
EXTRACT(YEAR FROM TO_DATE('99/10/11','RR/MM/DD')), EXTRACT(YEAR FROM TO_DATE('49/10/11','RR/MM/DD')),
EXTRACT(YEAR FROM TO_DATE('50/10/11','RR/MM/DD'))
FROM DUAL;


-- 8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';


-- 9번
SELECT ROUND(AVG(POINT),1) FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


-- 10번
SELECT DEPARTMENT_NO AS "학과번호", COUNT(*) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;


-- 11번
SELECT COUNT(*) AS "지도교수 없는 학생 수" FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;


-- 12번
SELECT SUBSTR(TERM_NO,1,4) AS 년도, ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'  
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;


-- 13번
SELECT DEPARTMENT_NO, COUNT(DECODE(ABSENCE_YN,'Y',1))  -- 널이 아닌값이 있으면 수를 셈
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;


-- 14번
SELECT  STUDENT_NAME AS "동일이름", COUNT(*) AS "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) >=2
ORDER BY 1;


-- 15번
SELECT NVL(SUBSTR(TERM_NO,1,4),' ') AS "년도", NVL(SUBSTR(TERM_NO,5,2),' ') AS "학기", ROUND(AVG(POINT),1) AS 평점 
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2));


SELECT * FROM TB_CLASS;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_GRADE;
